ProjectsResourcePlanner/Models/DomainModels/AllocationPeriod.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectsResourcePlanner.Models.DomainModels
{
    public class AllocationPeriod
    {
        public int AllocationPeriodId { get; set; }
        [MaxLength(150)]
        public string PeriodName { get; set; }

        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }

        public int WorkingDays { get; set; }
    }

    public class AllocationPeriodSelectModel
    {
        public int AllocationPeriodId { get; set; }
        public string PeriodName { get; set; }

        public AllocationPeriodSelectModel(AllocationPeriod allocationPeriod)
        {
            AllocationPeriodId = allocationPeriod.AllocationPeriodId;
            PeriodName = allocationPeriod.PeriodName;
        }
    }
}

ProjectsResourcePlanner/Controllers/AllocationPeriodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectsResourcePlanner.Data;
using ProjectsResourcePlanner.Models;
using ProjectsResourcePlanner.Models.DomainModels;

namespace ProjectsResourcePlanner.Controllers
{
    public class AllocationPeriodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AllocationPeriodsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: AllocationPeriods
        public async Task<IActionResult> Index()
        {
            return View(await _context.AllocationPeriods.ToListAsync());
        }

        // GET: AllocationPeriods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allocationPeriod = await _context.AllocationPeriods
                .FirstOrDefaultAsync(m => m.AllocationPeriodId == id);
            if (allocationPeriod == null)
            {
                return NotFound();
            }

            return View(allocationPeriod);
        }

        // GET: AllocationPeriods/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: AllocationPeriods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AllocationPeriodId,PeriodName,StartDate,EndDate,WorkingDays")] AllocationPeriod allocationPeriod)
        {
            if (ModelState.IsValid)
            {
                _context.Add(allocationPeriod);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(allocationPeriod);
        }

        // GET: AllocationPeriods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allocationPeriod = await _context.AllocationPeriods.FindAsync(id);
            if (allocationPeriod == null)
            {
                return NotFound();
            }
            return View(allocationPeriod);
        }

        // POST: AllocationPeriods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("AllocationPeriodId,PeriodName,StartDate,EndDate,WorkingDays")] AllocationPeriod allocationPeriod)
        {
            if (id != allocationPeriod.AllocationPeriodId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(allocationPeriod);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AllocationPeriodExists(allocationPeriod.AllocationPeriodId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(allocationPeriod);
        }

        // GET: AllocationPeriods/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var allocationPeriod = await _context.AllocationPeriods
                .FirstOrDefaultAsync(m => m.AllocationPeriodId == id);
            if (allocationPeriod == null)
            {
                return NotFound();
            }

            return View(allocationPeriod);
        }

        // POST: AllocationPeriods/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var allocationPeriod = await _context.AllocationPeriods.FindAsync(id);
            _context.AllocationPeriods.Remove(allocationPeriod);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AllocationPeriodExists(int id)
        {
            return _context.AllocationPeriods.Any(e => e.AllocationPeriodId == id);
        }

        public async Task<IActionResult> GetAllPeriods(string searchTerm)
        {
            var allocationPeriods = new List<AllocationPeriod>();
            if (!(string.IsNullOrEmpty(searchTerm) || string.IsNullOrWhiteSpace(searchTerm)))
            {
                allocationPeriods = await _context.AllocationPeriods
                    .Where(x => x.PeriodName.ToLowerInvariant().Contains(searchTerm.ToLowerInvariant())).ToListAsync();
            }
            
            var allocationPeriodSelectList = new List<AllocationPeriodSelectModel>();
            foreach (var allocationPeriod in allocationPeriods)
            {
                allocationPeriodSelectList.Add(new AllocationPeriodSelectModel(allocationPeriod));
            }

            return Json(new { items = allocationPeriodSelectList });
        }
    }
}

ProjectsResourcePlanner/Controllers/ProjectAllocationPeriodsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ProjectsResourcePlanner.Data;
using ProjectsResourcePlanner.Models;
using ProjectsResourcePlanner.Models.DomainModels;
using ProjectsResourcePlanner.Models.ViewModels;

namespace ProjectsResourcePlanner.Controllers
{
    public class ProjectAllocationPeriodsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProjectAllocationPeriodsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ProjectAllocationPeriods
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.ProjectAllocationPeriods.Include(p => p.AllocationPeriod).Include(p => p.PrimaryAllocatedMember).Include(p => p.Project).Include(p => p.SecondaryAllocatedMember).Include(p => p.TertiaryAllocatedMember);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: ProjectAllocationPeriods/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectAllocationPeriod = await _context.ProjectAllocationPeriods
                .Include(p => p.AllocationPeriod)
                .Include(p => p.PrimaryAllocatedMember)
                .Include(p => p.Project)
                .Include(p => p.SecondaryAllocatedMember)
                .Include(p => p.TertiaryAllocatedMember)
                .FirstOrDefaultAsync(m => m.ProjectId == id);
            if (projectAllocationPeriod == null)
            {
                return NotFound();
            }

            return View(projectAllocationPeriod);
        }

        // GET: ProjectAllocationPeriods/Create
        public IActionResult Create(int allocationPeriodId)
        {
            var allocationPeriod = _context.AllocationPeriods.Find(allocationPeriodId);

            var model = new ProjectAllocationPeriodViewModel(allocationPeriod);

            model.WorkOrdersInPeriod = _context.WorkOrders.Where(x => x.DueDate >= allocationPeriod.StartDate).ToList();
            model.AvailableMembersinPeriod = _context.MemberAllocationPeriods.Where(x => x.AllocationPeriodId == allocationPeriodId).ToList();
            model.Projects = _context.Projects.ToList();
            // model.AvailableHours = GetHoursForAllocationPeriod(allocationPeriod);
            model.ProjectAllocationPeriods = new List<ProjectAllocationPeriod>();

            foreach (var project in model.Projects)
            {
                var pap = new ProjectAllocationPeriod()
                {
                    AllocationPeriodId = allocationPeriod.AllocationPeriodId,
                    AllocationPeriod = allocationPeriod,
                    Hours = project.SLAHours,
                    ProjectId = project.ProjectId,
                    Project = project
                };
                model.ProjectAllocationPeriods.Add(pap);
            }
            ModelState.AddModelError("Member not specified", "Please ensure that a primary and secondary member has been specified for each project.");



            //ViewData["AllocationPeriodId"] = new SelectList(_context.AllocationPeriods, "AllocationPeriodId", "AllocationPeriodId");
            //ViewData["PrimaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            //ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId");
            //ViewData["SecondaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            //ViewData["TertiaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId");
            return View(model);
        }

        private int GetHoursForAllocationPeriod(AllocationPeriod allocationPeriod, ICollection<Member> members)
        {
            var totalHours = (allocationPeriod.WorkingDays * 8 * members.Count); // -Leave day hours
            return totalHours;
        }

        // POST: ProjectAllocationPeriods/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ICollection<ProjectAllocationPeriod> projectAllocationPeriodVm)
        {
            if (projectAllocationPeriodVm.Any(x => x.PrimaryAllocatedMemberId == 0 || x.SecondaryAllocatedMemberId == 0))
            {
                ModelState.AddModelError("Member not specified", "Please ensure that a primary and secondary member has been specified for each project.");
                var allocationPeriodId = projectAllocationPeriodVm.First().AllocationPeriodId;
                var allocationPeriod = _context.AllocationPeriods.Find(allocationPeriodId);
                var model = new ProjectAllocationPeriodViewModel(allocationPeriod);

                model.WorkOrdersInPeriod = _context.WorkOrders.Where(x => x.DueDate >= allocationPeriod.StartDate).ToList();
                model.AvailableMembersinPeriod = _context.MemberAllocationPeriods.Where(x => x.AllocationPeriodId == allocationPeriodId).ToList();
                model.Projects = _context.Projects.ToList();
                model.ProjectAllocationPeriods = new List<ProjectAllocationPeriod>();
                model.ProjectAllocationPeriods.AddRange(projectAllocationPeriodVm);

                return View(model);
            }
            if (ModelState.IsValid)
            {
                var projectAllocationPeriods = new List<ProjectAllocationPeriod>();
                foreach (var pap in projectAllocationPeriodVm)
                {
                    if (pap.PrimaryAllocatedMemberId == 0 || pap.SecondaryAllocatedMemberId == 0)
                    {
                        throw new Exception("Please specify a member in every column. No primary or secondary member specified for ProjectId: " + pap.ProjectId);
                    }
                    var papToAdd = new ProjectAllocationPeriod()
                    {
                        AllocationPeriodId = pap.AllocationPeriodId,
                        ProjectId = pap.ProjectId,
                        Hours = pap.Hours,
                        PrimaryAllocatedMemberId = pap.PrimaryAllocatedMemberId,
                        PrimaryAllocationPercentage = pap.PrimaryAllocationPercentage,
                        SecondaryAllocatedMemberId = pap.SecondaryAllocatedMemberId,
                        SecondaryAllocationPercentage = pap.SecondaryAllocationPercentage,
                        TertiaryAllocatedMemberId = pap.TertiaryAllocatedMemberId,
                        TertiaryAllocationPercentage = pap.TertiaryAllocationPercentage
                    };
                    projectAllocationPeriods.Add(papToAdd);
                }
                _context.Add(projectAllocationPeriodVm);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["AllocationPeriodId"] = new SelectList(_context.AllocationPeriods, "AllocationPeriodId", "AllocationPeriodId", projectAllocationPeriodVm.AllocationPeriodId);
            //ViewData["PrimaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriodVm.PrimaryAllocatedMemberId);
            //ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId", projectAllocationPeriodVm.ProjectId);
            //ViewData["SecondaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriodVm.SecondaryAllocatedMemberId);
            //ViewData["TertiaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriodVm.TertiaryAllocatedMemberId);
            return View(projectAllocationPeriodVm);
        }

        // GET: ProjectAllocationPeriods/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectAllocationPeriod = await _context.ProjectAllocationPeriods.FindAsync(id);
            if (projectAllocationPeriod == null)
            {
                return NotFound();
            }
            ViewData["AllocationPeriodId"] = new SelectList(_context.AllocationPeriods, "AllocationPeriodId", "AllocationPeriodId", projectAllocationPeriod.AllocationPeriodId);
            ViewData["PrimaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriod.PrimaryAllocatedMemberId);
            ViewData["ProjectId"] = new SelectList(_context.Projects, "ProjectId", "ProjectId", projectAllocationPeriod.ProjectId);
            ViewData["SecondaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriod.SecondaryAllocatedMemberId);
            ViewData["TertiaryAllocatedMemberId"] = new SelectList(_context.Members, "MemberId", "MemberId", projectAllocationPeriod.TertiaryAllocatedMemberId);
            return View(projectAllocationPeriod);
        }

        // POST: ProjectAllocationPeriods/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

ProjectsResourcePlanner/Views/AllocationPeriods/Create.cshtml
@model ProjectsResourcePlanner.Models.DomainModels.AllocationPeriod

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>AllocationPeriod</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PeriodName" class="control-label"></label>
                <input asp-for="PeriodName" class="form-control" />
                <span asp-validation-for="PeriodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingDays" class="control-label"></label>
                <input asp-for="WorkingDays" class="form-control" />
                <span asp-validation-for="WorkingDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsResourcePlanner/Views/AllocationPeriods/Delete.cshtml
@model ProjectsResourcePlanner.Models.DomainModels.AllocationPeriod

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>AllocationPeriod</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PeriodName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkingDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkingDays)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AllocationPeriodId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ProjectsResourcePlanner/Views/AllocationPeriods/Details.cshtml
@model ProjectsResourcePlanner.Models.DomainModels.AllocationPeriod

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>AllocationPeriod</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PeriodName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PeriodName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkingDays)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkingDays)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.AllocationPeriodId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ProjectsResourcePlanner/Views/AllocationPeriods/Edit.cshtml
@model ProjectsResourcePlanner.Models.DomainModels.AllocationPeriod

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>AllocationPeriod</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AllocationPeriodId" />
            <div class="form-group">
                <label asp-for="PeriodName" class="control-label"></label>
                <input asp-for="PeriodName" class="form-control" />
                <span asp-validation-for="PeriodName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkingDays" class="control-label"></label>
                <input asp-for="WorkingDays" class="form-control" />
                <span asp-validation-for="WorkingDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjectsResourcePlanner/Views/AllocationPeriods/Index.cshtml
@model IEnumerable<ProjectsResourcePlanner.Models.DomainModels.AllocationPeriod>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PeriodName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkingDays)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PeriodName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkingDays)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.AllocationPeriodId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.AllocationPeriodId">Details</a> |
                @*<a asp-controller="ProjectAllocationPeriods" asp-action="Create" asp-route-id="@item.AllocationPeriodId">Allocate</a> |*@
                @Html.ActionLink("Allocate", "Create", "ProjectAllocationPeriods", new { allocationPeriodId = item.AllocationPeriodId }) |
                <a asp-action="Delete" asp-route-id="@item.AllocationPeriodId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>